import { useState } from 'react'
import { batches, batchUrl, downloadFile, money } from './data'
import { useInvestor } from './state'
import { Back, Badge, Empty, Heading, Icon, Note, Panel, Stat } from './ui'

export function Settlements() {
  const [tab, setTab] = useState(new URLSearchParams(location.search).get('tab') === 'payouts' ? 'payouts' : 'statements')
  const exportCsv = () => downloadFile('crabshare-quyet-toan-demo.csv', 'DỮ LIỆU DEMO - KHÔNG PHẢI CHỨNG TỪ\nBatch,Vốn hoàn lại,Lãi phân bổ,Tổng tiền,Trạng thái\nCR-0626,20000000,1600000,21600000,Đã đối soát\nCR-0526,30000000,3360000,33360000,Đề xuất chưa duyệt', 'text/csv;charset=utf-8')
  return <><Heading title="Quyết toán & chi trả" description="Tách bạch vốn hoàn lại, kết quả phân bổ và tiền đã thực nhận." action={<button className="iv-button secondary" onClick={exportCsv}><Icon name="download" size={16}/>Xuất báo cáo CSV</button>}/><div className="iv-stats three"><Stat label="Đã nhận về" value="21,6 triệu" note="Đã đối soát từ nhà cung cấp" icon="bank"/><Stat label="Trong đó: vốn hoàn lại" value="20 triệu" note="Batch CR-0626 đã đóng" icon="bag"/><Stat label="Trong đó: lãi phân bổ" value="+1,6 triệu" note="Kết quả đã hoàn tất, không phải dự báo" icon="chart"/></div><Panel><div className="iv-tabs"><button className={tab === 'statements' ? 'active' : ''} onClick={() => setTab('statements')}>Bảng quyết toán</button><button className={tab === 'payouts' ? 'active' : ''} onClick={() => setTab('payouts')}>Lịch sử chi trả</button></div>{tab === 'statements' ? <div className="iv-table-wrap"><table className="iv-table"><thead><tr><th>Batch</th><th>Vốn của bạn</th><th>Lãi / lỗ phân bổ</th><th>Trạng thái</th><th>Chi tiết</th></tr></thead><tbody><tr><td><strong>CR-0526</strong><small>Cua thịt vụ đầu mùa</small></td><td>{money(30000000)}</td><td className="iv-positive">+{money(3360000)}<small>Dự kiến theo đề xuất</small></td><td><Badge tone="sand">Chờ phản hồi</Badge></td><td><a className="iv-text-link" href={batchUrl('settlement', 'CR-0526')}>Kiểm tra <Icon name="arrow" size={15}/></a></td></tr><tr><td><strong>CR-0626</strong><small>Cua gạch mùa hạ</small></td><td>{money(20000000)}</td><td className="iv-positive">+{money(1600000)}</td><td><Badge tone="sage">Đã chi trả</Badge></td><td><a className="iv-text-link" href={batchUrl('settlement', 'CR-0626')}>Xem chi tiết <Icon name="arrow" size={15}/></a></td></tr></tbody></table></div> : <><div className="iv-table-wrap"><table className="iv-table"><thead><tr><th>Ngày / giao dịch</th><th>Batch</th><th>Tổng nhận</th><th>Người nhận</th><th>Trạng thái</th></tr></thead><tbody><tr><td><strong>20/09/2026</strong><small>PAY-DEMO-0626</small></td><td>CR-0626</td><td>{money(21600000)}<small>Vốn 20 triệu · Lãi 1,6 triệu</small></td><td>Ngân hàng demo<small>•••• 3456 · tài khoản tại lúc chi trả</small></td><td><Badge tone="sage">Đã đối soát</Badge></td></tr></tbody></table></div><Note>Lịch sử lưu tài khoản nhận tại thời điểm giao dịch. Đề xuất CR-0526 chưa được duyệt nên chưa xuất hiện trong tiền đã nhận.</Note></>}</Panel></>
}

export function SettlementDetail() {
  const { state, setState, notify } = useInvestor(); const id = new URLSearchParams(location.search).get('batch') || 'CR-0526'; const b = batches.find(b => b.id === id)
  const [negative, setNegative] = useState(false); const [reason, setReason] = useState(''); const [form, setForm] = useState(false)
  if (!b || !['CR-0526', 'CR-0626'].includes(id)) return <><Back href="/investor/settlements">Quyết toán & chi trả</Back><Empty title="Batch chưa có bảng quyết toán" text="Bạn sẽ nhận thông báo khi đề xuất được công bố."/></>
  const paid = b.id === 'CR-0626'; const cost = b.cost; const revenue = negative ? cost - 80000000 : paid ? 440000000 : 696000000
  const pool = revenue - cost; const investorRatio = paid ? .8 : .7; const ratio = b.owned / b.target
  const result = negative ? -Math.min(b.owned, Math.round(Math.abs(pool) * ratio)) : Math.round(pool * investorRatio * ratio)
  const capital = b.owned - Math.max(0, -result); const gain = Math.max(0, result); const total = capital + gain
  const response = state.responses.find(r => r.batch === id)
  return <><Back href="/investor/settlements">Quyết toán & chi trả</Back><Heading eyebrow={`${id} / ${b.name}`} title="Bảng quyết toán của bạn" description={negative ? 'Kịch bản minh họa pool âm · Không phải quyết toán của Batch này' : paid ? 'Đã hoàn tất và đối soát ngày 20/09/2026' : 'Đề xuất v1.0 · Phản hồi trước 05/10/2026'} action={<Badge tone={paid && !negative ? 'sage' : 'sand'}>{negative ? 'Kịch bản lỗ minh họa' : paid ? 'Đã chi trả' : 'Đề xuất chưa duyệt'}</Badge>}/>
    <div className="iv-two-col"><div className="iv-stack"><Panel title="1. Kết quả toàn Batch" subtitle="Doanh thu đã đối soát và chi phí chuẩn khóa trước gọi vốn"><dl className="iv-statement-lines"><div><dt>Doanh thu bán hàng đã đối soát</dt><dd>{money(revenue)}</dd></div><div><dt>Chi phí chuẩn đã khóa · v1.0</dt><dd>− {money(cost)}</dd></div><div><dt>Điều chỉnh hoàn tiền / dự phòng / cọc</dt><dd>{money(0)}</dd></div><div className="total"><dt>Revenue Pool</dt><dd className={negative ? 'iv-negative' : ''}>{money(pool)}</dd></div></dl><details className="iv-disclosure"><summary>Nguồn doanh thu trong bộ dữ liệu mẫu</summary><p>Giá trị đơn đã hoàn tất và phân bổ bao tiêu đã đối soát, sau hủy/trả. Tiền cọc đang giữ chưa được tính là doanh thu.</p><p>Khoản điều chỉnh 0 ₫ chỉ áp dụng trong kịch bản này. Chi phí nền tảng do Operator trả ngoài quỹ Batch; không tự trừ thêm vào phần Investor.</p></details></Panel>
    <Panel title="2. Căn cứ phân bổ"><dl className="iv-details"><div><dt>Vốn của bạn / tổng vốn xác nhận</dt><dd>{money(b.owned)} / {money(b.target)}</dd></div><div><dt>Tỷ trọng của bạn</dt><dd>{(ratio * 100).toFixed(0)}%</dd></div><div><dt>{negative ? 'Quy tắc lỗ mẫu' : 'Tỷ lệ chia lãi cho nhóm Investor'}</dt><dd>{negative ? 'Lỗ phân bổ theo vốn, giới hạn ở vốn góp' : `${investorRatio * 100}%`}</dd></div><div><dt>{negative ? 'Phần lỗ của bạn' : 'Lãi phân bổ của bạn'}</dt><dd className={negative ? 'iv-negative' : 'iv-positive'}>{money(result)}</dd></div></dl><Note>{negative ? `Min(vốn góp; 80 triệu × ${ratio * 100}%) = ${money(-result)}. Đây là quy tắc lỗ giả định để minh họa UI, cần được chốt trong hợp đồng trước huy động.` : `${shortNumber(pool)} × ${investorRatio * 100}% × ${ratio * 100}% = ${money(result)}. Tỷ lệ từng Batch theo hồ sơ mẫu, không phải mức sinh lời bảo đảm.`}</Note><details className="iv-scenarios"><summary>Trải nghiệm tình huống pool âm</summary><label className="iv-check"><input type="checkbox" checked={negative} onChange={e => setNegative(e.target.checked)}/><span>Xem kịch bản lỗ giả định (không thay đổi dữ liệu danh mục)</span></label></details></Panel>
    {!paid && !negative && <Panel title="3. Kiểm tra và phản hồi" subtitle="Cửa sổ phản hồi mẫu đến 05/10/2026">{response ? <Note tone="success"><strong>Đã ghi nhận phản hồi của bạn</strong><p>{response.text}</p><p>Chờ xử lý trong bản demo. Bảng quyết toán chưa được coi là đã duyệt.</p></Note> : <><p className="iv-paragraph">Có điểm chưa rõ về doanh thu, chi phí hay cách chia? Gửi nội dung cụ thể để được đối chiếu trước khi duyệt.</p><button className="iv-button secondary" onClick={() => setForm(!form)}>{form ? 'Đóng biểu mẫu' : 'Gửi phản hồi về quyết toán'}</button>{form && <form className="iv-form iv-space-top" onSubmit={e => { e.preventDefault(); if (!reason.trim()) return; setState(s => ({ ...s, responses: [...s.responses, { batch: id, text: reason.trim() }] })); notify('Đã lưu phản hồi demo.') }}><label>Nội dung cần đối chiếu<textarea required minLength={10} maxLength={1500} value={reason} onChange={e => setReason(e.target.value)} placeholder="Ví dụ: Tôi muốn xem căn cứ doanh thu bao tiêu…"/></label><button className="iv-button">Gửi phản hồi</button></form>}</>}</Panel>}</div>
    <aside><Panel title="Phần của bạn" className="iv-sticky"><dl className="iv-statement-lines"><div><dt>Vốn đã góp</dt><dd>{money(b.owned)}</dd></div>{negative && <div><dt>Lỗ trừ vào vốn</dt><dd className="iv-negative">{money(result)}</dd></div>}<div><dt>Vốn hoàn lại</dt><dd>{money(capital)}</dd></div><div><dt>Lãi được phân bổ</dt><dd>{money(gain)}</dd></div><div><dt>Thuế / khấu trừ trong mẫu</dt><dd>{money(0)}</dd></div><div className="total"><dt>{paid && !negative ? 'Đã nhận' : 'Tổng theo kịch bản'}</dt><dd>{money(total)}</dd></div></dl><small className="iv-muted">Thuế 0 ₫ là giả định minh họa, không phải chính sách thuế đã xác minh.</small><button className="iv-button secondary full iv-space-top" onClick={() => downloadFile(`quyet-toan-demo-${id}.txt`, `CRABSHARE — QUYẾT TOÁN DEMO\n${negative ? 'KỊCH BẢN LỖ GIẢ ĐỊNH' : 'DỮ LIỆU MINH HỌA'}\nBatch: ${id}\nDoanh thu: ${money(revenue)}\nChi phí khóa: ${money(cost)}\nPool: ${money(pool)}\nVốn đã góp: ${money(b.owned)}\nVốn hoàn lại: ${money(capital)}\nLãi/lỗ phân bổ: ${money(result)}\nTổng: ${money(total)}\nKhông phải chứng từ thực tế.`)}><Icon name="download" size={16}/>Tải bảng giải thích</button></Panel></aside></div></>
}
function shortNumber(n: number) { return `${n / 1000000} triệu` }
